In [42]:
import pandas as pd
import os
import numpy as np

# 1. Data Loading

In [43]:
# open_path = 'D:\\공유폴더\\1_상권분석\\상권관련데이터\\결과분석\\12_1주차'
# close_path = 'D:\\공유폴더\\1_상권분석\\상권관련데이터\\결과분석\\12_2주차'
raw_data_path = '../data/Dataset/'
cluster_path = 'D:\\공유폴더\\1_상권분석\\상권관련데이터\\결과분석\\12_4주차'
preprocessing_folder_path = '../data/전처리 파일/회귀계수'

# open_list = os.listdir(open_path)
# close_list = os.listdir(close_path)
cluster_list = os.listdir(cluster_path)
file_list = [file_name for file_name in cluster_list if '.csv' in file_name]
file_list

['f2(total,mm,1221)).csv',
 'f2(total,raw,1222)).csv',
 'f2(평균영업기간,mm,1221).csv',
 'f2_expo(total,mm,1222)).csv']

In [44]:
pre_all_file = os.listdir(preprocessing_folder_path)
pre_file_list = [file_name for file_name in pre_all_file if ('.csv' and '1221') in file_name]
pre_file_list

['MGWR 회귀계수(평균영업기간,mm,data_1221).csv',
 'MGWR 회귀계수(평균폐업기간,mm,data_1221).csv',
 'MGWR 회귀계수(평균폐업기간,mm,e1.5,data_1221).csv',
 'MGWR 회귀계수(평균폐업기간,mm,e2,data_1221).csv',
 'MGWR 회귀계수(평균폐업기간,mm,e2,raw,data_1221).csv',
 'MGWR 회귀계수(평균폐업기간,mm,q2,data_1221).csv']

In [45]:
dataset_list = os.listdir(raw_data_path)
dataset_list

['fixed_dataset(매출건수).csv',
 'fixed_dataset(자동차유지,10퍼센트절사평균).csv',
 'fixed_dataset(자동차제거,null유지).csv',
 'fixed_dataset(자동차제거,매출log,null유지).csv',
 'fixed_dataset(자동차제거,매출log,null유지,절사평균).csv',
 'fixed_dataset(자동차제거,매출raw,null유지).csv',
 'fixed_dataset(자동차제거,매출raw,null유지,1126).csv',
 'fixed_dataset(자동차제거,매출raw,null유지,1201).csv',
 'fixed_dataset(자동차제거,매출raw,null유지,원래연면적,1201).csv',
 'fixed_dataset(자동차제거,매출raw,null유지,원래연면적,버퍼점포밀도,1202).csv',
 'fixed_dataset.csv',
 'fixed_dataset_1105.csv',
 'fixed_dataset_1214.csv']

In [46]:
# open_cluster = 'renew_f1(total,bw120,local_mul_RFE,1202).csv'
# close_cluster = 'f1(평균폐업기간,Q3,maxbw113,local_mul_RF,1207).csv'
cluster = 'f2_expo(total,mm,1222)).csv'
close_coef = 'MGWR 회귀계수(평균폐업기간,mm,expo,data_1222).csv'
open_coef = 'MGWR 회귀계수(평균영업기간,mm,data_1221).csv'
raw_data_name = 'fixed_dataset_1214.csv'

# open_cluster_data = pd.read_csv(os.path.join(open_path,open_cluster))
# close_cluster_data = pd.read_csv(os.path.join(close_path,close_cluster))
cluster_data = pd.read_csv(os.path.join(cluster_path,cluster))
open_coef_data = pd.read_csv(os.path.join(preprocessing_folder_path,open_coef),encoding='euc-kr')
close_coef_data = pd.read_csv(os.path.join(preprocessing_folder_path,close_coef),encoding='euc-kr')
raw_data = pd.read_csv(os.path.join(raw_data_path,raw_data_name),encoding='euc-kr')

In [47]:
# display(open_cluster_data)
# display(close_cluster_data)
display(cluster_data)
display(open_coef_data)
display(close_coef_data)
display(raw_data)

,BAS_ID,open_7cluster,open_8cluster,open_9cluster,open_10cluster,open_11cluster,open_12cluster,open_13cluster,open_14cluster,open_15cluster,...,close_21cluster,close_22cluster,close_23cluster,close_24cluster,close_25cluster,close_26cluster,close_27cluster,close_28cluster,close_29cluster,close_30cluster
0,21300,5,2,2,2,2,2,0,13,13,...,14.0,14.0,14.0,14.0,14.0,6.0,6.0,6.0,6.0,6.0
1,21301,6,6,6,6,6,6,6,2,2,...,4.0,4.0,4.0,4.0,1.0,1.0,0.0,5.0,2.0,2.0
2,21302,6,6,6,6,6,6,6,2,2,...,4.0,4.0,4.0,4.0,1.0,1.0,0.0,5.0,2.0,2.0
3,21303,6,6,6,6,6,6,6,2,2,...,4.0,4.0,4.0,4.0,1.0,1.0,0.0,5.0,2.0,2.0
4,21304,6,6,6,6,6,6,6,2,2,...,4.0,4.0,4.0,4.0,1.0,1.0,0.0,5.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,21455,3,3,8,3,1,0,12,12,12,...,13.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0
154,21456,1,1,1,0,7,3,3,3,1,...,11.0,11.0,5.0,5.0,5.0,5.0,5.0,2.0,0.0,29.0
155,21457,4,4,4,4,4,4,4,4,4,...,7.0,3.0,3.0,1.0,0.0,14.0,14.0,14.0,14.0,14.0
156,21458,4,4,4,4,4,4,4,4,4,...,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0
157,21459,4,4,4,4,4,4,4,4,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,intercept,주거인구/직장인구,아파트 가구수,단독주택 비율,서비스업매출비율,외식업매출비율,근린생활시설 비율,평균최근접역거리,(주거인구+직장인구) / 유동인구,공동주택 비율,평균 도로 길이,도로길이고려_전체통합도,평균최근접정류장거리,점포밀도,도로율,상가밀도,x,y,BAS_ID
0,101.621097,-19.987889,-16.801620,65.704605,14.014662,-5.626208,23.586274,35.361611,17.711248,40.306141,-23.904455,3.311235,-35.622408,-19.685987,-6.035367,30.520389,126.689135,37.518708,21300
1,101.588382,-23.890852,-8.773298,62.139227,13.830890,-5.889719,23.802630,35.318115,17.663914,40.324000,-23.854534,3.292138,-35.577028,-20.044021,-6.141908,29.879127,126.695459,37.522417,21301
2,101.522925,-25.789394,-5.523626,59.192299,13.568331,-6.112244,23.785570,35.243342,17.511612,40.228112,-23.972543,3.123871,-35.527580,-20.232580,-6.288905,29.235275,126.701342,37.522339,21302
3,101.521680,-24.057234,-10.941299,61.390775,13.604052,-5.993951,23.585937,35.249103,17.485549,40.168892,-24.069333,3.058700,-35.539301,-19.990565,-6.257364,29.536470,126.698730,37.518981,21303
4,101.489663,-25.927305,-8.067665,58.775076,13.453254,-6.175319,23.636990,35.200969,17.435722,40.154172,-24.076259,2.997333,-35.520551,-20.167782,-6.342535,29.049711,126.703419,37.519319,21304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,101.245787,21.224317,-24.982116,81.376537,13.441081,-4.954238,20.847649,35.116662,16.353710,38.960687,-26.599721,1.491737,-35.138179,-17.696100,-6.251154,31.653166,126.692372,37.471208,21455
154,101.005612,-26.704756,-31.688316,74.597850,12.198783,-6.271569,21.307287,34.845402,15.500597,38.473790,-26.768097,0.723165,-34.839900,-18.363022,-6.742205,30.076730,126.723687,37.476074,21456
155,100.869224,-43.321240,-53.173870,62.917525,11.516640,-7.025526,22.215082,34.753040,14.861097,38.292458,-26.611846,0.423437,-34.507010,-19.367136,-7.177739,28.595270,126.749377,37.478546,21457
156,100.929799,-39.837053,-45.371749,66.149594,11.769030,-6.842123,21.657555,34.663485,15.339811,38.480290,-26.562386,0.614864,-34.912496,-18.943958,-6.993857,29.259096,126.731154,37.483105,21458
157,100.908172,-41.499135,-50.286377,67.892868,11.744293,-6.739841,21.906847,34.824721,14.972537,38.291671,-26.761885,0.456836,-34.519328,-18.954073,-7.012409,29.325957,126.742914,37.474121,21459

,intercept,주거인구/직장인구,아파트 가구수,단독주택 비율,서비스업매출비율,외식업매출비율,근린생활시설 비율,평균최근접역거리,(주거인구+직장인구) / 유동인구,공동주택 비율,평균 도로 길이,도로길이고려_전체통합도,평균최근접정류장거리,점포밀도,도로율,상가밀도,x,y,BAS_ID
0,151.264879,-5.238827,-46.911252,-20.844823,-11.341123,17.774693,-19.926163,23.390043,40.270026,-23.026908,-37.479826,37.653454,-38.080706,-49.805779,-60.447495,21.965062,126.689135,37.518708,21300
1,151.035092,-5.543051,-46.470206,-22.109593,-11.612787,17.337794,-20.014619,18.105730,40.085887,-23.616709,-38.245800,36.372476,-38.946650,-50.106434,-60.704185,21.886960,126.695459,37.522417,21301
2,150.976756,-5.731691,-46.108959,-22.975735,-11.729160,17.125273,-20.061096,18.012791,40.117643,-23.637341,-38.237395,35.541592,-39.254053,-50.185732,-60.641445,21.934654,126.701342,37.522339,21302
3,151.083284,-5.605787,-46.398559,-22.242451,-11.479891,17.395410,-20.026757,20.790439,40.107657,-23.411511,-37.904206,36.204107,-38.917310,-49.813567,-60.520392,22.058178,126.698730,37.518981,21303
4,151.013013,-5.786546,-46.069467,-23.098041,-11.634563,17.130483,-20.159779,19.851785,40.160051,-23.509329,-37.941858,35.424835,-39.348700,-49.765520,-60.510959,22.082958,126.703419,37.519319,21304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,151.395115,-7.438801,-50.778131,-18.634023,-10.220309,19.778145,-24.971379,23.228574,35.457602,-22.120099,-34.602698,31.088007,-42.011067,-47.627029,-58.895796,21.810539,126.695939,37.469443,21454
147,151.531921,-6.795386,-50.743120,-17.318772,-9.918154,20.171147,-24.620378,28.450677,35.785188,-21.863470,-34.442564,31.943651,-41.266300,-47.589110,-58.634670,21.939653,126.692372,37.471208,21455
148,150.961595,-8.153860,-49.277348,-24.535644,-10.677632,18.598955,-25.510162,2.952195,35.937287,-23.220756,-35.284842,26.295302,-44.976936,-45.484527,-59.534403,23.966985,126.723687,37.476074,21456
149,150.411583,-8.791076,-48.105093,-28.958609,-13.716084,17.876986,-24.165716,-18.577073,35.737319,-24.364403,-38.555009,24.719201,-46.410943,-45.332648,-60.020664,24.702902,126.749377,37.478546,21457
150,150.853220,-8.139178,-48.121574,-27.149484,-11.190480,18.423086,-24.278224,0.632320,36.396285,-23.706861,-35.178024,25.443803,-44.260029,-44.936590,-59.814106,24.767657,126.731154,37.483105,21458

,BAS_ID,BAS_AR,도로길이고려_전체통합도,도로길이고려_국부통합도_R3,기초구역평균_전체통합도,기초구역평균_국부통합도_R3,도로율,평균 도로 길이,아파트시세변화_차분평균,평균영업기간,...,서비스업종다양성,소매업종다양성,상가밀도,주중 / 주말,06 to 18 / 18 to 06,개별공시지가 변화 차분평균,(주거인구+직장인구) / 유동인구,주거인구/직장인구,10_30 / 40_60,점포밀도
0,21300,0.743330,617.130076,7987.604945,0.060037,0.907932,7.332336,119.253463,0.000000,163.106482,...,1.609438,2.390980,86.099041,2.342449,2.695669,31337.73585,0.268398,0.149563,0.406896,7.046875
1,21301,0.121045,221.397046,2876.534944,0.069661,0.938454,30.948119,211.340833,305.909000,156.249615,...,1.127535,1.985080,346.978396,2.315147,2.280277,344640.00000,0.254881,0.667946,0.439757,11.523810
2,21302,0.175777,341.252878,4162.583064,0.087372,1.084619,25.546905,214.144187,0.000000,111.950730,...,2.029155,1.314799,876.110071,2.064957,2.339853,174949.46240,0.220317,0.899425,0.508371,143.584416
3,21303,0.270679,475.038010,6080.093135,0.084712,1.079401,15.517121,105.011320,912.500000,153.728003,...,2.364045,2.064017,232.748015,2.273528,2.246297,97041.79104,0.108296,6.308614,0.441902,36.111111
4,21304,0.073319,273.241567,3575.514233,0.092931,1.107098,32.713927,134.361765,369.231000,177.329451,...,2.289920,2.379112,2495.942389,2.016228,2.004099,166589.33650,0.212989,1.959390,0.479893,113.836066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,21456,1.340721,339.514691,2241.934926,0.179476,0.910954,3.660437,184.741846,0.000000,55.406477,...,0.000000,0.000000,2.983469,1.449448,3.640312,178750.00000,0.027235,0.013054,0.451702,3.000000
157,21457,0.268643,546.088235,5760.159505,0.097563,0.969282,21.446923,224.758790,64.032000,123.192430,...,2.245035,2.397922,186.120614,2.072345,2.291081,96794.24460,0.133531,3.087848,0.535500,7.160000
158,21458,0.197292,263.517281,3222.709021,0.084734,1.061010,14.367906,152.046143,812.941333,122.109657,...,2.293040,1.930021,359.872676,2.105405,1.587592,51441.28440,0.403526,16.585638,0.603346,37.450704
159,21459,2.648838,337.993901,3090.876012,0.090934,0.890338,0.013953,49.053500,0.000000,165.177930,...,0.000000,0.693147,1.132572,1.931703,2.096614,263150.00000,0.000691,0.000000,0.536289,2.666667
160,21460,0.750104,97.076149,1563.939199,0.052723,0.843960,0.139354,174.217000,0.000000,NaN,...,NaN,NaN,NaN,1.885383,2.233427,3350.00000,0.000000,0.000000,0.481442,NaN

In [100]:
col = ['주거인구/직장인구', '아파트 가구수', '단독주택 비율', '서비스업매출비율', '외식업매출비율', '근린생활시설 비율','평균최근접역거리'
    ,'(주거인구+직장인구) / 유동인구','공동주택 비율', '평균 도로 길이', '도로길이고려_전체통합도', '평균최근접정류장거리', '점포밀도', '도로율','상가밀도']

extracted_data = raw_data.loc[:,['BAS_ID']+col]

In [49]:
# open_merge_data = open_coef_data.merge(open_cluster_data.loc[:,['BAS_ID','open_13cluster']],how='inner',right_on='BAS_ID',left_on='BAS_ID')
# close_merge_data = close_coef_data.merge(close_cluster_data.loc[:,['BAS_ID','close_13cluster']],how='inner',right_on='BAS_ID',left_on='BAS_ID')

open_merge_data = open_coef_data.merge(cluster_data.loc[:,['BAS_ID','open_15cluster']],how='inner',right_on='BAS_ID',left_on='BAS_ID')
close_merge_data = close_coef_data.merge(cluster_data.loc[:,['BAS_ID','close_15cluster']],how='inner',right_on='BAS_ID'
                                         ,left_on='BAS_ID')
open_raw_merge_data = extracted_data.merge(cluster_data.loc[:,['BAS_ID','open_15cluster']],how='inner',right_on='BAS_ID'
                                           ,left_on='BAS_ID')
close_raw_merge_data = extracted_data.merge(cluster_data.loc[:,['BAS_ID','close_15cluster']],how='inner',right_on='BAS_ID'
                                      ,left_on='BAS_ID')

# 2. 상대적 상권 유형

In [66]:
open_kind_data = open_merge_data.copy()
close_kind_data = close_merge_data.copy()

In [67]:
# 상대적인 상권활성도 컬럼-open
for col in list(open_kind_data)[:16]:
    for idx, data in enumerate(open_kind_data[col]):
        mean = open_kind_data[col].mean()
        # 평균이 0보다 큰 경우
        if mean > 0:
            if data > mean:
                open_kind_data.loc[idx,'open_kind_'+col] = 'H_p'
            else:
                open_kind_data.loc[idx,'open_kind_'+col] = 'L_p'
        # 평균이 0보다 같거나 작은 경우
        else:
            if data > mean:
                open_kind_data.loc[idx,'open_kind_'+col] = 'L_m'
            else:
                open_kind_data.loc[idx,'open_kind_'+col] = 'H_m'

In [68]:
open_kind_data = open_kind_data.loc[:,'BAS_ID':]

In [1]:
# 상대적인 상권활성도 컬럼-open
for col in list(close_kind_data)[:16]:
    for idx, data in enumerate(close_kind_data[col]):
        mean = close_kind_data[col].mean()

        # 평균이 0보다 큰 경우
        if mean > 0:
            if data > mean:
                close_kind_data.loc[idx,'close_kind_'+col] = 'H_p'
            else:
                close_kind_data.loc[idx,'close_kind_'+col] = 'L_p'
        # 평균이 0보다 같거나 작은 경우
        else:
            if data > mean:
                close_kind_data.loc[idx,'close_kind_'+col] = 'L_m'
            else:
                close_kind_data.loc[idx,'close_kind_'+col] = 'H_m'

In [70]:
close_kind_data = close_kind_data.loc[:,'BAS_ID':]

In [71]:
int_kind_data = open_kind_data.merge(close_kind_data,how='left',right_on='BAS_ID',left_on='BAS_ID')

for col in list(int_kind_data.iloc[:,2:18]):
    split_col = col.split('_')
    if len(split_col) == 3:
        int_kind_data[split_col[-1]] = int_kind_data[col]+int_kind_data['_'.join(['close',split_col[1],split_col[2]])]
    elif len(split_col) == 4:
        int_kind_data['_'.join([split_col[2],split_col[3]])] = int_kind_data[col]+int_kind_data['_'.join(['close',split_col[1],split_col[2]
                                                                                        ,split_col[3]])]

In [132]:
int_kind_data.loc[:,['open_15cluster','close_15cluster','근린생활시설 비율']][int_kind_data['open_15cluster'].isin({13})]

    open_15cluster  close_15cluster 근린생활시설 비율
0               13             14.0    H_pL_m
6               13              9.0    H_pL_m
7               13             14.0    H_pL_m
8               13             14.0    H_pL_m
9               13              9.0    H_pL_m
13              13              9.0    H_pL_m
61              13              9.0    H_pL_m
62              13              9.0    H_pL_m
63              13              3.0    H_pL_m
67              13             14.0    H_pL_m
69              13             14.0    H_pL_m
75              13              3.0    L_pL_m
85              13              1.0    L_pH_m

In [98]:
import math

In [101]:
int_kind_data = int_kind_data.loc[:,['BAS_ID','open_15cluster','close_15cluster']+col]
int_kind_data['close_15cluster'] = int_kind_data['close_15cluster'].apply(lambda x : -1 if math.isnan(x) else x)

In [121]:
al_LL = ['H_pH_p','L_mH_p','H_pL_m','L_mL_m']
al_LH = ['H_pL_p','H_pH_m','L_mL_p','L_mH_m']
al_HL = ['L_pH_p','L_pL_m','H_mH_p','H_mL_m']
al_HH = ['L_pL_p','L_pH_m','H_mL_p','H_mH_m']

# al_kind = [(al_LL,'창업이 더 저조, 폐업이 더 저조'),
#            (al_LH,'창업이 더 저조, 폐업이 덜 저조'),
#            (al_HL,'창업이 덜 저조, 폐업이 더 저조'),
#            (al_HH,'창업이 덜 저조, 폐업이 덜 저조')]

# al_kind = [(al_LL,'상대적 상권 순환 저조'),
#            (al_LH,'상대적 상권 축소'),
#            (al_HL,'상대적 상권 확장'),
#            (al_HH,'상대적 상권 순환 활발')]

al_kind = [(al_HH,'1'),
           (al_LL,'2'),
           (al_LH,'3'),
           (al_HL,'4')
           ]

def classify_kind(kind):
    for kind_set, msg in al_kind:
        if kind is np.nan:
            return ''

        if kind in kind_set:
            return msg

In [122]:
interpret_kind = pd.DataFrame(columns=int_kind_data.columns,index=int_kind_data.index)

for i, row in int_kind_data.iloc[:,3:].iterrows():
    for j, kind in enumerate(row):
        interpret_kind.iloc[i,j+3] = classify_kind(kind)

interpret_kind['BAS_ID'] = int_kind_data['BAS_ID']
interpret_kind['open_15cluster'] = int_kind_data['open_15cluster']
interpret_kind['close_15cluster'] = int_kind_data['close_15cluster']

In [112]:
interpret_kind.to_csv('../data/결과 데이터/기초구역별 상권 유형도 해석.csv',encoding='euc-kr',index=False)

In [2]:
open_group = pd.DataFrame(index=sorted(list(int_kind_data['open_15cluster'].unique())))
close_group = pd.DataFrame(index=sorted(list(int_kind_data['close_15cluster'].unique())))
display(open_group)
display(close_group)

In [125]:
table = str.maketrans('{}\'\'','    ')

for col in list(interpret_kind)[3:]:
    open_msg_group = interpret_kind.groupby('open_15cluster')[col].apply(lambda x:"%s" % '|'.join(x))
    close_msg_group = interpret_kind.groupby('close_15cluster')[col].apply(lambda x:"%s" % '|'.join(x))
    open_msg = []
    close_msg = []

    for i in open_msg_group.index:
        open_msg.append(set(open_msg_group.loc[i].split('|')))
    open_group.loc[:,col] = pd.Series([str(msg).translate(table).replace(' ','') for msg in open_msg])
    open_group.loc[:,col]=open_group.loc[:,col].apply(lambda x: x[1:] if x.startswith(',') else x)

    for i in close_msg_group.index:
        close_msg.append(set(close_msg_group.loc[i].split('|')))

    close_group.loc[:,col] = pd.Series([str(msg).translate(table).replace(' ','') for msg in close_msg],index=close_msg_group.index)
    close_group.loc[:,col]=close_group.loc[:,col].apply(lambda x: x[1:] if x.startswith(',') else x)

In [126]:
close_group

,주거인구/직장인구,아파트 가구수,단독주택 비율,서비스업매출비율,외식업매출비율,근린생활시설 비율,평균최근접역거리,(주거인구+직장인구) / 유동인구,공동주택 비율,평균 도로 길이,도로길이고려_전체통합도,평균최근접정류장거리,점포밀도,도로율,상가밀도
-1.0,,,,,,,,,,,,,,,
0.0,"1,4","2,4",1,1,1,"3,2,1,4","3,1","2,1,4","3,1","3,1","3,2,1","3,1","4,1",1,"4,1"
1.0,"3,1","3,2,1,4","3,2,1","4,1","4,2,1","1,4","3,1","3,1,4","3,4,1","3,2,4",1,"3,4,1","2,4","4,2,1","2,4"
2.0,1,"1,4","3,1",1,"4,1","3,1",1,1,1,"4,1",1,3,"2,4",4,"2,4"
3.0,"2,4","3,2","2,1","3,2","3,1","2,4",2,2,"3,2",3,2,4,"3,1",3,"3,1"
4.0,"3,2",3,2,2,2,1,2,"3,1","2,4",4,"2,4","3,2,4","3,2",2,3
5.0,"1,4",2,1,"3,1",1,"2,4","2,1,4",2,3,3,"3,2","1,4",1,"3,1","4,1"
6.0,3,3,2,"2,4",2,1,"3,1","3,1",4,4,"3,1","3,2","3,2","3,2","3,2"
7.0,1,1,3,1,1,"3,1",1,1,1,1,1,3,"2,4",4,4
8.0,4,4,1,1,1,2,1,4,"3,1",3,3,3,1,1,1
9.0,"2,4","3,2","2,4",2,3,2,2,2,"3,2",3,2,4,"3,1",3,"3,1"
10.0,1,1,3,1,1,3,1,1,1,1,1,3,2,4,4
11.0,"3,2",3,2,2,2,1,"3,2","3,1","2,4","2,4","2,1","2,4","3,2","3,2",3
12.0,"3,2",3,2,2,2,1,2,"3,1",4,4,4,"3,2","3,2",2,3
13.0,"3,2","3,1",2,2,2,1,2,3,"2,4",4,"2,4",2,3,2,3
14.0,2,"3,2",2,2,"3,2",2,2,2,2,"3,2",2,4,"3,1",3,3

In [127]:
open_group_T = open_group.transpose()
close_group_T = close_group.transpose()

In [128]:
FILE_KIND = 'Label Encoding'
with pd.ExcelWriter('../data/결과 데이터/상대적인 상권 유형도 해석('+FILE_KIND+').xlsx') as writer:
    open_group_T.to_excel(writer, sheet_name='운영평균영업개월')
    close_group_T.to_excel(writer, sheet_name='폐업평균영업개월')

In [ ]:
int_kind_data.to_csv('../data/결과 데이터/상대적인 상권 유형도.csv',index=False,encoding='euc-kr')

In [59]:
drop_index = close_raw_merge_data[close_raw_merge_data['close_15cluster'].isnull()].index
close_raw_merge_data = close_raw_merge_data.drop(drop_index,axis=0).fillna(0)
close_raw_merge_data.shape

(151, 17)

In [13]:
# open data
open_data = open_merge_data.drop(['x','y','BAS_ID'],axis=1)
open_result = pd.pivot_table(open_data,index='open_15cluster',aggfunc=np.mean)
open_result

,(주거인구+직장인구) / 유동인구,intercept,공동주택 비율,근린생활시설 비율,단독주택 비율,도로길이고려_전체통합도,도로율,상가밀도,서비스업매출비율,아파트 가구수,외식업매출비율,점포밀도,주거인구/직장인구,평균 도로 길이,평균최근접역거리,평균최근접정류장거리
open_15cluster,,,,,,,,,,,,,,,,
0,16.395536,101.058911,39.304655,22.017713,50.319229,1.423296,-7.007139,28.028843,11.961793,-19.489021,-7.357711,-19.717054,-34.026195,-25.307770,34.463988,-35.614507
1,15.714645,100.978389,38.621229,21.316165,67.845827,0.769155,-6.901812,29.542496,11.906482,-26.670117,-6.815736,-18.674456,-28.303805,-26.385961,34.587216,-35.170513
2,17.387564,101.459342,40.132438,23.620966,56.750928,2.924518,-6.414165,28.777682,13.326330,-7.166138,-6.319145,-20.274266,-26.564156,-24.104469,35.148620,-35.521279
3,15.946712,100.996367,39.218368,23.319112,35.347241,1.527401,-7.359812,25.627368,11.643044,-27.319809,-7.538967,-21.103251,-37.621662,-25.185262,34.591363,-35.262749
4,15.146498,100.876640,38.460902,22.009965,59.574392,0.540163,-7.179846,28.431498,11.510700,-51.010384,-7.156946,-19.420055,-43.203878,-26.458535,34.592671,-34.863906
5,15.440667,100.849530,38.796940,22.336491,41.789857,0.781104,-7.411307,26.956586,11.275861,-42.562642,-7.694913,-20.304057,-43.834701,-25.952556,34.331944,-35.319423
6,16.638894,101.246505,39.261459,21.887162,70.585814,1.755465,-6.536893,30.146957,12.797045,-21.330407,-6.193865,-18.754508,-11.067486,-25.424334,34.917490,-35.337604
7,15.704172,100.891265,38.839479,21.713570,50.023092,0.784859,-7.221403,27.931330,11.459832,-33.284467,-7.573202,-19.639211,-43.217131,-26.010986,34.275556,-35.511625
8,16.387309,101.103972,39.489277,23.236244,38.685097,1.861638,-7.124777,26.280951,12.032738,-11.827804,-7.301322,-20.852727,-34.708608,-24.921028,34.685234,-35.400124
9,15.663956,100.926666,39.138853,24.158561,28.325477,1.557572,-7.738052,23.677872,11.241353,-39.203641,-7.942079,-22.219817,-38.205889,-24.982409,34.564572,-35.088214
10,15.502382,100.937693,38.544229,21.476631,66.023838,0.655682,-6.980580,29.303320,11.767774,-37.268632,-6.910709,-18.864025,-37.227045,-26.488945,34.579697,-35.085340
11,16.297576,101.194592,38.958853,21.309303,77.344954,1.425357,-6.470146,30.739227,12.919397,-22.110956,-5.681830,-18.214725,4.586248,-26.178331,34.992384,-35.138111
12,16.514978,101.260064,39.089707,21.225395,79.481632,1.633907,-6.343949,31.126077,13.246003,-23.033157,-5.344099,-18.056961,17.780962,-26.114633,35.067817,-35.209117
13,17.345393,101.441418,39.940987,22.891700,63.589229,2.653479,-6.351399,29.717125,13.333824,-17.861887,-6.146878,-19.484737,-19.827227,-24.371585,35.099019,-35.553025
14,16.631711,101.169399,39.653746,23.293647,40.786609,2.082449,-7.002027,26.761146,12.257609,-1.826803,-7.172664,-20.798300,-32.711166,-24.733482,34.756443,-35.450531

In [14]:
# close data
close_data = close_merge_data.drop(['x','y','BAS_ID'],axis=1)
close_result = pd.pivot_table(close_data,index='close_15cluster',aggfunc=np.mean)
close_result

,(주거인구+직장인구) / 유동인구,intercept,공동주택 비율,근린생활시설 비율,단독주택 비율,도로길이고려_전체통합도,도로율,상가밀도,서비스업매출비율,아파트 가구수,외식업매출비율,점포밀도,주거인구/직장인구,평균 도로 길이,평균최근접역거리,평균최근접정류장거리
close_15cluster,,,,,,,,,,,,,,,,
0.0,38.730610,150.492465,-24.208974,-22.286668,-28.882860,26.765009,-60.567430,23.138032,-14.555793,-46.109570,16.851117,-47.383357,-7.729409,-38.504958,2.785768,-43.905451
1.0,37.145680,150.788624,-23.764824,-23.711279,-27.095318,25.843611,-60.100321,24.660594,-11.846689,-47.874831,18.165027,-45.369611,-8.281192,-35.477889,3.051862,-43.474293
2.0,36.318399,150.554465,-24.245586,-23.743029,-28.987307,25.014408,-60.023546,24.889056,-13.407749,-47.755930,17.863195,-45.215067,-8.575578,-37.282791,-7.406623,-45.306869
3.0,39.336665,150.782954,-23.521458,-21.711022,-24.545573,32.017123,-60.764656,22.242816,-12.424375,-46.340796,16.924437,-48.846117,-6.756935,-37.487020,15.465720,-40.666250
4.0,36.013835,151.279702,-22.452623,-24.589923,-20.441873,29.931893,-59.315203,22.481889,-10.636606,-50.518685,19.742698,-47.238565,-7.941692,-34.474394,14.826520,-41.405774
5.0,39.392576,150.619360,-23.785177,-21.754472,-27.603668,29.680326,-60.732617,22.456538,-13.597072,-45.361679,16.470343,-48.415865,-7.208441,-38.031261,11.382498,-42.307180
6.0,36.467176,151.045478,-23.059603,-24.376471,-23.657405,27.035128,-59.911977,23.242241,-11.253642,-49.767671,19.293348,-46.605581,-7.982795,-34.336563,5.211573,-41.739542
7.0,35.895366,150.418238,-24.383738,-23.993578,-29.063590,24.814502,-60.031748,24.727819,-13.835114,-47.986541,17.834448,-45.353437,-8.721588,-38.516437,-16.477254,-46.241455
8.0,38.953998,150.388902,-24.523418,-21.996308,-29.654015,27.044273,-60.568035,22.531234,-15.129065,-46.415977,16.765292,-48.124451,-7.060637,-39.987874,-3.807289,-44.454886
9.0,40.019620,151.011410,-23.416557,-20.531411,-22.569089,35.206242,-60.537058,22.111365,-11.678379,-46.422237,17.210443,-49.507026,-5.877296,-37.671323,20.008892,-39.365455
10.0,35.866241,150.338297,-24.405637,-24.096709,-29.196942,24.564941,-60.030864,24.645852,-14.136180,-48.020050,17.793780,-45.411718,-8.689125,-39.295969,-23.350818,-46.806686
11.0,36.958531,151.049659,-22.849665,-23.865209,-22.187173,29.230493,-60.209537,22.332549,-11.504657,-49.741597,19.157300,-47.944609,-7.396776,-34.722710,9.830638,-40.257094
12.0,35.567666,151.346956,-22.282827,-24.855989,-19.296999,30.719008,-59.047926,22.056181,-10.323900,-50.759651,19.722949,-47.492288,-7.930806,-34.603105,20.863377,-41.815944
13.0,36.083319,151.508300,-21.953701,-24.280870,-17.676862,32.266692,-58.953127,21.986660,-10.256640,-50.636265,20.050822,-47.750098,-7.109047,-34.313210,27.386930,-40.434959
14.0,40.113596,151.267988,-22.850406,-20.755108,-19.729500,36.569635,-60.287928,22.140297,-11.221657,-47.461777,18.020079,-49.202771,-5.087173,-36.704786,24.448418,-38.273852

# 3. 회귀계수 집계 및 결과 출력

In [61]:
# open raw data
agg_open_raw_data = open_raw_merge_data.drop(['BAS_ID'],axis=1)
open_raw_result = pd.pivot_table(agg_open_raw_data,index='open_15cluster',aggfunc=np.mean)
open_raw_result

,(주거인구+직장인구) / 유동인구,공동주택 비율,근린생활시설 비율,단독주택 비율,도로길이고려_전체통합도,도로율,상가밀도,서비스업매출비율,아파트 가구수,외식업매출비율,점포밀도,주거인구/직장인구,평균 도로 길이,평균최근접역거리,평균최근접정류장거리
open_15cluster,,,,,,,,,,,,,,,
0,0.264005,29.466667,25.383333,3.866667,334.779282,41.514630,3391.738374,0.308196,545.000000,0.336243,123.920974,6.068332,139.161715,0.354018,0.065764
1,0.203023,28.416667,35.100000,7.150000,384.379325,24.881209,3516.293505,0.313725,46.666667,0.404219,258.036721,5.214145,116.494965,0.297191,0.144471
2,0.321506,27.745455,43.445455,10.281818,412.789604,25.944015,975.404252,0.169480,376.909091,0.331330,62.082070,2.094998,252.628434,1.271759,0.094466
3,0.423620,54.155556,34.077778,10.427778,315.240371,23.678509,811.366535,0.207675,1403.833333,0.239685,54.238751,15.735079,223.578239,0.820163,0.081660
4,0.339308,42.085000,25.765000,20.935000,361.583228,28.289680,1107.323022,0.224627,374.200000,0.217867,50.020457,6.005160,150.611094,0.702916,0.090099
5,0.699962,55.480000,20.260000,10.900000,484.448458,28.429648,990.992342,0.215245,788.600000,0.207112,40.659170,8.117044,161.226945,0.844877,0.067212
6,0.238843,46.977778,18.166667,9.822222,363.229738,19.446939,684.400139,0.273923,867.666667,0.269647,46.580511,8.146973,141.584241,0.932235,0.063142
7,0.298389,32.560000,28.240000,3.100000,463.549947,46.458342,3836.755058,0.211364,28.400000,0.374435,138.191505,3.169025,156.640081,0.490346,0.063020
8,0.336465,26.808333,24.875000,27.991667,303.326489,34.916703,1786.947464,0.167396,354.833333,0.363162,70.536866,28.952282,192.613261,0.486006,0.077215
9,0.017735,0.000000,100.000000,0.000000,441.854330,5.175969,12.245031,0.055887,0.000000,0.068313,2.666667,0.012871,313.440900,1.491184,0.119186
10,0.177916,19.200000,17.800000,11.433333,229.955054,26.861369,1408.480282,0.519661,62.000000,0.275457,74.126013,2.804625,200.997353,0.393096,0.082315
11,0.346249,39.984000,24.336000,24.468000,308.657356,24.215918,1106.567983,0.184138,291.800000,0.291943,55.931489,10.538971,124.356073,0.489988,0.083448
12,0.295996,36.050000,32.241667,25.216667,250.267048,32.716678,882.450807,0.131897,294.750000,0.292181,46.243022,7.986932,154.653249,0.763428,0.072362
13,0.543877,38.361538,30.053846,21.138462,464.762355,21.135997,1014.795918,0.131708,1372.384615,0.229677,72.022456,10.454945,151.231259,1.386692,0.124836
14,0.526942,63.316667,27.850000,6.983333,227.326033,30.124198,1034.180139,0.144507,1323.666667,0.237823,42.176672,15.972775,209.700874,0.433466,0.093388

In [62]:
# close raw data
agg_close_raw_data = close_raw_merge_data.drop(['BAS_ID'],axis=1)
close_raw_result = pd.pivot_table(agg_close_raw_data,index='close_15cluster',aggfunc=np.mean)
close_raw_result

,(주거인구+직장인구) / 유동인구,공동주택 비율,근린생활시설 비율,단독주택 비율,도로길이고려_전체통합도,도로율,상가밀도,서비스업매출비율,아파트 가구수,외식업매출비율,점포밀도,주거인구/직장인구,평균 도로 길이,평균최근접역거리,평균최근접정류장거리
close_15cluster,,,,,,,,,,,,,,,
0.0,0.458682,50.811111,26.729630,12.951852,366.441555,30.395577,1547.120928,0.228491,888.666667,0.297927,70.179241,22.014362,173.438322,0.586474,0.070326
1.0,0.272754,32.870370,24.674074,7.733333,370.981373,34.436652,3077.832179,0.295290,271.629630,0.317199,149.407077,5.193141,148.803351,0.413484,0.086751
2.0,0.403001,45.710000,25.380000,26.570000,333.443747,30.641936,1364.204749,0.217689,469.400000,0.243962,59.646478,6.766103,131.531422,0.469636,0.080140
3.0,0.395653,46.840000,41.260000,1.620000,520.419182,22.441724,827.131408,0.162299,2860.000000,0.360036,63.936388,8.959695,319.449435,0.758353,0.097299
4.0,0.375059,36.987500,39.000000,21.500000,189.459498,18.060341,1065.208535,0.202139,287.375000,0.429997,59.986070,9.789293,130.702261,0.328705,0.099497
5.0,0.374861,42.742857,25.464286,13.785714,294.119188,31.254803,1064.048470,0.188773,991.071429,0.286146,48.520372,9.915296,176.165505,0.439649,0.080894
6.0,0.248007,48.971429,13.700000,13.942857,373.017837,20.986163,804.681859,0.320581,373.142857,0.141213,50.987012,10.426150,109.596855,0.423343,0.063240
7.0,0.104380,36.200000,52.200000,11.650000,466.813491,27.720749,337.954144,0.071518,359.500000,0.019748,21.683093,2.048089,189.306628,1.151946,0.085632
8.0,0.449369,52.250000,26.350000,18.683333,300.790723,19.580472,438.679593,0.128343,1672.166667,0.150044,37.914812,17.521197,263.419175,1.273273,0.115196
9.0,0.364521,25.966667,38.760000,15.980000,381.953344,27.287533,1235.425189,0.172287,545.000000,0.318260,71.386050,5.003461,188.229619,1.514352,0.094334
10.0,0.045959,0.000000,5.600000,6.800000,186.960213,3.612566,100.629943,0.274380,0.000000,0.063490,9.244444,0.083010,389.903000,1.589194,0.111174
11.0,0.334881,43.566667,17.183333,20.583333,401.370188,37.103879,960.406306,0.066751,271.666667,0.241967,38.482793,8.591500,159.215019,0.821089,0.089349
12.0,0.330858,37.462500,23.887500,30.512500,235.354712,31.391922,1703.798334,0.222549,256.750000,0.378785,74.290639,7.437713,111.450132,0.381320,0.070744
13.0,0.235056,24.800000,39.200000,33.137500,303.262828,30.757802,777.465158,0.116047,62.000000,0.188952,44.614029,3.748071,155.932527,0.768111,0.075660
14.0,0.559828,48.471429,27.314286,23.942857,493.966906,13.580290,425.237493,0.137462,345.428571,0.194630,36.668684,8.655109,131.492230,1.720101,0.128826

In [65]:
with pd.ExcelWriter(os.path.join(preprocessing_folder_path,'군집별 데이터 집계 결과.xlsx')) as writer:
    open_result.to_excel(writer, sheet_name='평균영업기간 회귀계수')
    close_result.to_excel(writer, sheet_name='평균폐업기간 회귀계수')
    open_raw_result.to_excel(writer, sheet_name='평균영업기간 데이터')
    close_raw_result.to_excel(writer, sheet_name='평균폐업기간 데이터')

# 4. 군집별 유사도 - 평균 영업 기간

In [16]:
sign_to_binary = []
nrows, ncols = open_result.shape

for i in range(nrows):
    str_bi = ''
    for j in range(ncols):
        if open_result.iloc[i,j] > 0:
            str_bi += '1'
        else:
            str_bi += '0'
    sign_to_binary.append(str_bi)

In [17]:
sign_to_binary

['1111110110000010',
 '1111110110000010',
 '1111110110000010',
 '1111110110000010',
 '1111110110000010',
 '1111110110000010',
 '1111110110000010',
 '1111110110000010',
 '1111110110000010',
 '1111110110000010',
 '1111110110000010',
 '1111110110001010',
 '1111110110001010',
 '1111110110000010',
 '1111110110000010']

In [18]:
binary_matrix = pd.DataFrame(columns=open_result.index, index=open_result.index)

for i in range(nrows):
    for j in range(nrows):
        if sign_to_binary[i] == sign_to_binary[j]:
            binary_matrix.iloc[i,j] = 1
        else:
            binary_matrix.iloc[i,j] = 0

In [19]:
binary_matrix

open_15cluster 0  1  2  3  4  5  6  7  8  9  10 11 12 13 14
open_15cluster
0               1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
1               1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
2               1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
3               1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
4               1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
5               1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
6               1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
7               1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
8               1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
9               1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
10              1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
11              0  0  0  0  0  0  0  0  0  0  0  1  1  0  0
12              0  0  0  0  0  0  0  0  0  0  0  1  1  0  0
13              1  1  1  1  1  1  1  1  1  1  1  0  0  1  1
14              1  1  1  1  1  1  1  1  1  1  1  0  0  1  1

# 5. 군집별 유사도 - 평균 폐업 기간

In [9]:
close_result.head()

,BAS_AR,intercept,근린생활시설 비율,단독주택 비율,서비스업매출비율,소매업매출월평균변화량,외식업매출월평균변화량,주거인구/직장인구,평균최근접역거리,평균최근접정류장거리
close_15cluster,,,,,,,,,,
0.0,37.484311,119.559601,-0.035558,0.913826,14.189127,4.277148e-08,-1.172997e-06,0.449099,0.291454,-152.101811
1.0,13.090677,121.300348,-0.123401,-0.028538,-44.856654,5.989388e-08,-3.068776e-07,-0.048818,-5.262582,-148.219289
2.0,25.207013,127.962418,-0.444209,0.033726,-3.919305,4.029412e-07,-5.396841e-07,-0.020533,-9.011266,-25.911795
3.0,100.599677,128.156368,-0.558634,0.364367,-25.143538,-6.512515e-07,-2.205110e-06,-0.231503,-5.426936,-4.143740
4.0,7.252565,124.664593,-0.289493,-0.498876,-5.182131,5.069952e-08,3.309512e-07,0.188140,-6.608839,-72.636632

In [10]:
sign_to_binary = []
nrows, ncols = close_result.shape

for i in range(nrows):
    str_bi = ''
    for j in range(ncols):
        if close_result.iloc[i,j] > 0:
            str_bi += '1'
        else:
            str_bi += '0'
    sign_to_binary.append(str_bi)

In [11]:
sign_to_binary

['1101110110',
 '1100010000',
 '1101010000',
 '1101000000',
 '1100011100',
 '1101000000',
 '1100010000',
 '1101000000',
 '1101000000',
 '1100010000',
 '1101011100',
 '0100001000',
 '1101000000',
 '1100111100',
 '1100011100']

In [13]:
binary_matrix = pd.DataFrame(columns=close_result.index, index=close_result.index)

for i in range(nrows):
    for j in range(nrows):
        if sign_to_binary[i] == sign_to_binary[j]:
            binary_matrix.iloc[i,j] = 1
        else:
            binary_matrix.iloc[i,j] = 0

In [14]:
binary_matrix

close_15cluster,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0
close_15cluster,,,,,,,,,,,,,,,
0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1.0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0
2.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3.0,0,0,0,1,0,1,0,1,1,0,0,0,1,0,0
4.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
5.0,0,0,0,1,0,1,0,1,1,0,0,0,1,0,0
6.0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0
7.0,0,0,0,1,0,1,0,1,1,0,0,0,1,0,0
8.0,0,0,0,1,0,1,0,1,1,0,0,0,1,0,0
9.0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0
10.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
11.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
12.0,0,0,0,1,0,1,0,1,1,0,0,0,1,0,0
13.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
14.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1